drop user token class
TankerHQ/identity-cs pull request #4
Opened 2020-02-17 14:01 UTC by AlexandreBossard

2020-02-17 16:39 UTC, dmerejkowsky approved these changes

2020-02-17 16:57 UTC, dmerejkowsky approved these changes

2020-02-18 09:30 UTC, maximerety requested changes

2020-02-18 09:30 UTC, maximerety commented on Identity/PermanentIdentity.cs
> +        private SecretPermanentIdentity(UserToken userToken, string appId = "")
What does it have to do with dropping user token class? Split in another commit?

2020-02-18 09:30 UTC, maximerety commented on Identity.Tests/Helpers.cs
> +            var token = new SecretPermanentIdentity(TrustchainId, TrustchainPrivateKey, UserId);
Rename `token`?

2020-02-18 09:30 UTC, maximerety commented on Identity.Tests/Identity.cs
> +            string encodedToken = Helpers.GenerateTestPermanentIdentity();
Keeping the `token` wording everywhere is confusing. Rename to `identity`?

2020-02-18 09:30 UTC, maximerety commented on Identity/Identity.csproj
> +    <Copyright>Copyright ©  2020</Copyright>
Keep `2019`, or change to `Copyright © 2019-2020`. The whole point of copyright is to reference the initial year as a priority date!

Also remove the double space 😉

2020-02-18 10:43 UTC, maximerety approved these changes

2020-02-18 10:45 UTC, merged